# Generated by Django 5.2.7 on 2025-11-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='anonimous', max_length=50, verbose_name='Имя пользователя')),
                ('action', models.CharField(max_length=300, verbose_name='Действие')),
                ('method', models.CharField(choices=[('P', 'POST'), ('G', 'GET')], max_length=1, verbose_name='Метод')),
                ('path', models.CharField(max_length=300, verbose_name='Путь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
            ],
        ),
    ]
