# Generated by Django 5.2.7 on 2025-11-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_alter_log_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.PositiveSmallIntegerField(default=400, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
